import Vue from "vue";
import 'vant/lib/index.css';

import { 
        Button,
        Tabbar,
        TabbarItem,
        Icon,
        NavBar,
        SubmitBar,
        Checkbox,
        CheckboxGroup,
        Search,
        Swipe,
        SwipeItem,
        Grid,
        GridItem,
        Image,
        Divider,
        Lazyload,
        PullRefresh,
        List,
        NoticeBar,
        GoodsAction,
        GoodsActionButton,
        GoodsActionIcon,
        Sku,
        SwipeCell,
        Card,
        Stepper,
        Toast,
        Empty,
        Form,
        Field,
        ActionSheet,
        Cell,
        CellGroup,
        Uploader,
        Dialog,
        AddressEdit,
        AddressList,
        Area,
        Tab,
        Tabs,
        Step,
        Steps,
        Popup,

        } from 'vant';

Vue.use(Step);
Vue.use(Popup);
Vue.use(Steps);
Vue.use(Button);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Area);
Vue.use(AddressEdit);
Vue.use(AddressList);
Vue.use(Dialog);
Vue.use(Uploader);
Vue.use(ActionSheet);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Empty);
Vue.use(Form);
Vue.use(Field);
Vue.use(SwipeCell);
Vue.use(Stepper);
Vue.use(Sku);
Vue.use(Toast);
Vue.use(Card);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(NoticeBar);
Vue.use(PullRefresh);
Vue.use(List);
Vue.use(Lazyload);
Vue.use(Image);
Vue.use(Divider);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Icon);
Vue.use(NavBar);
Vue.use(SubmitBar);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Search);
Vue.use(Swipe);
Vue.use(SwipeItem);